ruby '2.4.2'
 
source 'https://rubygems.org'
 
gem 'sinatra'
gem 'sinatra-cross_origin'
gem 'json'
gem 'activerecord'
gem 'pg'
gem 'sinatra-activerecord'
gem 'rake'

group :development do
  gem 'shotgun'
end

group :test, :development do
  gem 'rack-test', require: 'rack/test'
  gem 'rspec'
  gem 'factory_bot'
  gem 'faker'
  gem 'pry'
  gem 'database_cleaner'
end
