source 'https://rubygems.org'

ruby '2.4.2'

gem 'rails', '4.2.8'
gem 'pg', '~> 0.21'
gem 'pry-rails'
gem 'spring', group: :development

gem 'faraday'
gem 'whenever', require: false
gem 'sidekiq'

gem 'event_bg_bus'
