#
# Autogenerated by Thrift Compiler (0.10.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

class Product
  include ::Thrift::Struct, ::Thrift::Struct_Union
  ID = 1
  NAME = 2
  PRICE = 3
  AMOUNT = 4

  FIELDS = {
    ID => {:type => ::Thrift::Types::I32, :name => 'id'},
    NAME => {:type => ::Thrift::Types::STRING, :name => 'name'},
    PRICE => {:type => ::Thrift::Types::I32, :name => 'price'},
    AMOUNT => {:type => ::Thrift::Types::I32, :name => 'amount'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

