# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4f780256e474328acd869d12b85705ae595f4157dcf8d178311b4db618d31938719052a53f704ca796054614b7b2e12e7ceaefe3ed2522e582ebfd0366f0c95

test:
  secret_key_base: 04d9bc9165808a61171f30e10582053e3c018293ddf04b1424a13b7427b9d7d96d4e2f07c5a8bd40f9103362bead923bea595cd1e06e7bf6e91fc66547ebfab8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
