default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

production:
  <<: *default
  database: todo
  username: todo
  password: todo

development:
  <<: *default
  database: todo

test:
  <<: *default
  database: todo_test
