# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3eeee81a79f2c43f08182c7ee111127ef2b48716c87bf4edd1054f32c3bd5c858ad17c8e6523e88e3eb0e0bbfa3f03d06b17a7214932a7537b92ad118a6f45a0

test:
  secret_key_base: a013f97f6095d3eae46366f72aa0153a6b2821df8535ee2cc0d63e22b4b53ca8ef2f343ef7d57ef1993ae529b93594dc3e4fcc4d870b245e81b607f72abae628

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
